import { Theme, OverlayStyle, CompletionStatus } from "./types";

export const GITHUB_DB_BASE_URL = "https://raw.githubusercontent.com/batureren/achievement-scavenger-database/main/games";
export const THEMES_URL = "https://raw.githubusercontent.com/batureren/achievement-scavenger-database/main/themes.json";

export const BUILTIN_THEMES: Theme[] = [
  { id: "default", name: "Dark (Default)", vars: { "--bg-color": "#18181b", "--card-bg": "#27272a", "--text-main": "#f4f4f5", "--text-muted": "#a1a1aa", "--accent-green": "#34d399", "--accent-red": "#ef4444", "--accent-yellow": "#f59e0b", "--border-color": "#3f3f46" } },
  { id: "midnight-blue", name: "Midnight Blue", vars: { "--bg-color": "#0f172a", "--card-bg": "#1e293b", "--text-main": "#e2e8f0", "--text-muted": "#94a3b8", "--accent-green": "#38bdf8", "--accent-red": "#f87171", "--accent-yellow": "#fbbf24", "--border-color": "#334155" } },
];

export const OVERLAY_STYLES: { id: OverlayStyle; name: string; icon: string; desc: string; preview: string }[] = [
  { id: "default",  name: "Default",   icon: "◼", desc: "Solid theme panels",               preview: "tile-preview--default"  },
  { id: "ghost",    name: "Ghost HUD", icon: "◻", desc: "Minimalist, flat left-bar accents",preview: "tile-preview--ghost"    },
  { id: "mmo",      name: "Quest Log", icon: "⚔", desc: "Borderless list with diamond bullets", preview: "tile-preview--mmo"  },
  { id: "neon",     name: "Neon Arc",  icon: "⚡", desc: "Sci-fi chamfered edges & inner glow", preview: "tile-preview--neon" },
  { id: "tactical", name: "Tactical",  icon: "◈", desc: "Terminal scanlines & [brackets]",  preview: "tile-preview--tactical" },
  { id: "frosted",  name: "Frosted",   icon: "❄", desc: "Heavy blur & highly rounded glass", preview: "tile-preview--frosted" },
];

export const COMPLETION_CONFIG: Record<CompletionStatus, { label: string; color: string; bg: string }> = {
  complete:    { label: "Complete",    color: "#a78bfa", bg: "rgba(167,139,250,0.12)" },
  in_progress: { label: "In Progress", color: "#34d399", bg: "rgba(52,211,153,0.12)"  },
  not_started: { label: "Not Started", color: "#a1a1aa", bg: "rgba(161,161,170,0.10)" },
  abandoned:   { label: "Abandoned",   color: "#f87171", bg: "rgba(248,113,113,0.12)" },
};

export const COMPLETION_KEYS: Record<string, string> = {
  complete: "lib.complete", in_progress: "lib.in_progress",
  not_started: "lib.not_started", abandoned: "lib.abandoned",
};

export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English" }, { code: "zh-CN", name: "简体中文 (Simplified Chinese)" },
  { code: "zh-TW", name: "繁體中文 (Traditional Chinese)" }, { code: "ja", name: "日本語 (Japanese)" },
  { code: "ko", name: "한국어 (Korean)" }, { code: "ru", name: "Русский (Russian)" },
  { code: "tr", name: "Türkçe (Turkish)" }, { code: "de", name: "Deutsch (German)" },
  { code: "fr", name: "Français (French)" }, { code: "es", name: "Español (Spanish)" },
  { code: "es-419", name: "Español - Latinoamérica (Spanish - LATAM)" },
  { code: "pt-BR", name: "Português - Brasil (Portuguese - Brazil)" },
  { code: "pt-PT", name: "Português (Portuguese - Portugal)" }, { code: "it", name: "Italiano (Italian)" },
  { code: "pl", name: "Polski (Polish)" }, { code: "uk", name: "Українська (Ukrainian)" },
  { code: "cs", name: "Čeština (Czech)" }, { code: "nl", name: "Nederlands (Dutch)" },
  { code: "th", name: "ไทย (Thai)" }, { code: "vi", name: "Tiếng Việt (Vietnamese)" }
];

export const STEAM_LANG_MAP: Record<string, string> = {
  "en": "english", "zh-CN": "schinese", "zh-TW": "tchinese", "ja": "japanese", "ko": "koreana",
  "ru": "russian", "tr": "turkish", "de": "german", "fr": "french", "es": "spanish",
  "es-419": "latam", "pt-BR": "brazilian", "pt-PT": "portuguese", "it": "italian",
  "pl": "polish", "uk": "ukrainian", "cs": "czech", "nl": "dutch", "th": "thai", "vi": "vietnamese"
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  "en": {
    "menu.view": "View", "menu.themes": "Themes", "menu.accounts": "Accounts", "menu.alwaysOnTop": "Always on Top (Overlay)", "menu.overlayWarning": "⚠️ For overlay use, set your game to Borderless Windowed", "menu.miniMode": "Compact Mini Mode", "menu.windowMode": "Window Mode", "menu.opacity": "Window Opacity", "menu.uiScale": "UI Scale", "menu.language": "Language (Database & UI)", "menu.sound": "Unlock Sound", "menu.keys": "🔑 Manage API Keys", "menu.startup": "Run on System Startup", "menu.screenshots": "Screenshots Folder",
    "filter.all": "All", "filter.locked": "Locked", "filter.unlocked": "Unlocked", "filter.tracked": "Tracked", "filter.missable": "⚠️ Missable", "filter.spoilers": "👁 Spoilers", "filter.guided": "🛡 Guided Mode", "filter.guidedOn": "🛡 Guided Mode (ON)", "menu.links": "Links",
    "search.achievements": "Search achievements...", "search.library": "🔍 Search games...",
    "lib.title": "Library Dashboard", "lib.empty": "No games match this filter.", "lib.all": "All", "lib.in_progress": "In Progress", "lib.complete": "Complete", "lib.not_started": "Not Started", "lib.abandoned": "Abandoned", "lib.last_played": "Last Played", "lib.name_az": "Name A–Z", "lib.most_complete": "Most Complete", "lib.least_complete": "Least Complete",
    "status.live": "Live", "status.offline": "Offline", "status.unlocked": "Unlocked",
    "stat.avgCompletion": "Avg. Global Completion", "stat.rarityDist": "Rarity Distribution (Total)",
    "accordion.stats": "Stats & Rarity", "accordion.shortcuts": "My Shortcuts & Tools",
    "sort.api": "API Order", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Rarest First", "sort.common": "Most Common First", "sort.chapter": "Chapter Order",
    "card.achievements": "achievements", "card.play": "▶ Play", "card.rarest": "⭐ Rarest:", "card.running": "Running Now",
    "chap.all": "All Chapters", "chap.none": "-- No Chapter --", "chap.fallback": "No Chapter",
    "btn.edit_db": "Edit DB", "btn.close_edit": "✕ Close Edit", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Create PR", "btn.add": "Add", "btn.add_chapter": "Add Chapter",
    "input.title": "Title", "input.url": "https://...", "input.new_chapter": "New Chapter Name...",
    "sec.shortcuts": "My Shortcuts", "sec.chapters": "📑 Chapter Index Manager", "sec.no_chapters": "No chapters defined.", "sec.session": "⏱ Session Unlocks", "sec.guides": "📚 Community Guides",
    "db.available": "✓ Community DB available", "db.missing": "⚠ No community DB — be the first to contribute"
  },
  "tr": {
    "menu.view": "Görünüm", "menu.themes": "Temalar", "menu.accounts": "Hesaplar", "menu.alwaysOnTop": "Her Zaman Üstte", "menu.overlayWarning": "⚠️ Arayüz (Overlay) kullanımı için oyunu Çerçevesiz Pencere moduna alın", "menu.miniMode": "Kompakt Mini Mod", "menu.windowMode": "Pencere Modu", "menu.opacity": "Pencere Saydamlığı", "menu.uiScale": "Arayüz Ölçeği", "menu.language": "Arayüz Dili", "menu.sound": "Kilit Açma Sesi", "menu.keys": "🔑 API Anahtarlarını Yönet", "menu.startup": "Sistem Başlangıcında Çalıştır", "menu.screenshots": "Ekran Görüntüleri Klasörü",
    "filter.all": "Tümü", "filter.locked": "Kilitli", "filter.unlocked": "Kazanılan", "filter.tracked": "İzlenen", "filter.missable": "⚠️ Kaçırılabilir", "filter.spoilers": "👁 Sürprizbozan", "filter.guided": "🛡 Rehberli Mod", "filter.guidedOn": "🛡 Rehberli Mod (AÇIK)", "menu.links": "Bağlantılar",
    "search.achievements": "Başarımlarda ara...", "search.library": "🔍 Oyunlarda ara...",
    "lib.title": "Kütüphane Panosu", "lib.empty": "Bu filtreye uyan oyun yok.", "lib.all": "Tümü", "lib.in_progress": "Devam Ediyor", "lib.complete": "Tamamlandı", "lib.not_started": "Başlanmadı", "lib.abandoned": "Bırakıldı", "lib.last_played": "Son Oynanan", "lib.name_az": "İsim A–Z", "lib.most_complete": "En Çok Tamamlanan", "lib.least_complete": "En Az Tamamlanan",
    "status.live": "Aktif", "status.offline": "Çevrimdışı", "status.unlocked": "Kazanılan",
    "stat.avgCompletion": "Ort. Küresel Tamamlanma", "stat.rarityDist": "Nadirlik Dağılımı (Toplam)",
    "accordion.stats": "İstatistikler ve Nadirlik", "accordion.shortcuts": "Kısayollarım ve Araçlar",
    "sort.api": "API Sırası", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "En Nadir İlk", "sort.common": "En Yaygın İlk", "sort.chapter": "Bölüm Sırası",
    "card.achievements": "başarım", "card.play": "▶ Oyna", "card.rarest": "⭐ En Nadir:", "card.running": "Şu An Açık",
    "chap.all": "Tüm Bölümler", "chap.none": "-- Bölüm Yok --", "chap.fallback": "Bölüm Yok",
    "btn.edit_db": "DB Düzenle", "btn.close_edit": "✕ Kapat", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "PR Oluştur", "btn.add": "Ekle", "btn.add_chapter": "Bölüm Ekle",
    "input.title": "Başlık", "input.url": "https://...", "input.new_chapter": "Yeni Bölüm Adı...",
    "sec.shortcuts": "Kısayollarım", "sec.chapters": "📑 Bölüm Dizini Yöneticisi", "sec.no_chapters": "Bölüm tanımlanmadı.", "sec.session": "⏱ Oturum Başarımları", "sec.guides": "📚 Topluluk Rehberleri",
    "db.available": "✓ Topluluk Veritabanı mevcut", "db.missing": "⚠ Topluluk Veritabanı yok — ilk katkıda bulunan siz olun"
  },
  "de": {
    "menu.view": "Ansicht", "menu.themes": "Designs", "menu.accounts": "Konten", "menu.alwaysOnTop": "Immer im Vordergrund", "menu.overlayWarning": "⚠️ Für Overlay-Nutzung Rahmenlosen Fenstermodus nutzen", "menu.miniMode": "Mini-Modus", "menu.windowMode": "Fenstermodus", "menu.opacity": "Transparenz", "menu.uiScale": "UI-Skalierung", "menu.language": "Sprache", "menu.sound": "Freischalt-Sound", "menu.keys": "🔑 API-Schlüssel verwalten", "menu.startup": "Beim Systemstart ausführen", "menu.screenshots": "Screenshots-Ordner",
    "filter.all": "Alle", "filter.locked": "Gesperrt", "filter.unlocked": "Freigeschaltet", "filter.tracked": "Verfolgt", "filter.missable": "⚠️ Verpassbar", "filter.spoilers": "👁 Spoiler", "filter.guided": "🛡 Geführter Modus", "filter.guidedOn": "🛡 Geführt (AN)", "menu.links": "Links",
    "search.achievements": "Erfolge suchen...", "search.library": "🔍 Spiele suchen...",
    "lib.title": "Bibliothek", "lib.empty": "Keine Spiele gefunden.", "lib.all": "Alle", "lib.in_progress": "Im Gange", "lib.complete": "Abgeschlossen", "lib.not_started": "Nicht gestartet", "lib.abandoned": "Abgebrochen", "lib.last_played": "Zuletzt gespielt", "lib.name_az": "Name A–Z", "lib.most_complete": "Meiste Erfolge", "lib.least_complete": "Wenigste Erfolge",
    "status.live": "Live", "status.offline": "Offline", "status.unlocked": "Freigeschaltet",
    "stat.avgCompletion": "Durchschn. Abschluss", "stat.rarityDist": "Seltenheitsverteilung",
    "accordion.stats": "Statistiken & Seltenheit", "accordion.shortcuts": "Meine Verknüpfungen",
    "sort.api": "API-Reihenfolge", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Seltenste zuerst", "sort.common": "Häufigste zuerst", "sort.chapter": "Kapitel",
    "card.achievements": "Erfolge", "card.play": "▶ Spielen", "card.rarest": "⭐ Seltenste:", "card.running": "Läuft gerade",
    "chap.all": "Alle Kapitel", "chap.none": "-- Kein Kapitel --", "chap.fallback": "Kein Kapitel",
    "btn.edit_db": "DB bearbeiten", "btn.close_edit": "✕ Schließen", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "PR erstellen", "btn.add": "Hinzufügen", "btn.add_chapter": "Kapitel hinzufügen",
    "input.title": "Titel", "input.url": "https://...", "input.new_chapter": "Neuer Kapitelname...",
    "sec.shortcuts": "Verknüpfungen", "sec.chapters": "📑 Kapitel-Manager", "sec.no_chapters": "Keine Kapitel.", "sec.session": "⏱ Sitzungserfolge", "sec.guides": "📚 Leitfäden",
    "db.available": "✓ Community-DB verfügbar", "db.missing": "⚠ Keine Community-DB"
  },
  "fr": {
    "menu.view": "Affichage", "menu.themes": "Thèmes", "menu.accounts": "Comptes", "menu.alwaysOnTop": "Toujours au premier plan", "menu.overlayWarning": "⚠️ Utilisez le mode Fenêtré sans bordure pour l'overlay", "menu.miniMode": "Mode Mini Compact", "menu.windowMode": "Mode Fenêtre", "menu.opacity": "Opacité", "menu.uiScale": "Échelle UI", "menu.language": "Langue", "menu.sound": "Son de déverrouillage", "menu.keys": "🔑 Gérer les clés API", "menu.startup": "Lancer au démarrage du système", "menu.screenshots": "Dossier Captures d'écran",
    "filter.all": "Tous", "filter.locked": "Verrouillé", "filter.unlocked": "Déverrouillé", "filter.tracked": "Suivi", "filter.missable": "⚠️ Manquable", "filter.spoilers": "👁 Spoilers", "filter.guided": "🛡 Mode Guidé", "filter.guidedOn": "🛡 Mode Guidé (ACTIF)", "menu.links": "Liens",
    "search.achievements": "Rechercher des succès...", "search.library": "🔍 Rechercher des jeux...",
    "lib.title": "Bibliothèque", "lib.empty": "Aucun jeu trouvé.", "lib.all": "Tous", "lib.in_progress": "En cours", "lib.complete": "Terminé", "lib.not_started": "Non commencé", "lib.abandoned": "Abandonné", "lib.last_played": "Dernière session", "lib.name_az": "Nom A–Z", "lib.most_complete": "Le plus terminé", "lib.least_complete": "Le moins terminé",
    "status.live": "En jeu", "status.offline": "Hors ligne", "status.unlocked": "Déverrouillé",
    "stat.avgCompletion": "Achèvement moyen global", "stat.rarityDist": "Distribution de la rareté",
    "accordion.stats": "Statistiques et rareté", "accordion.shortcuts": "Mes Raccourcis",
    "sort.api": "Ordre API", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Plus rares d'abord", "sort.common": "Plus communs d'abord", "sort.chapter": "Ordre des chapitres",
    "card.achievements": "succès", "card.play": "▶ Jouer", "card.rarest": "⭐ Plus rare:", "card.running": "En cours d'exécution",
    "chap.all": "Tous les chapitres", "chap.none": "-- Aucun chapitre --", "chap.fallback": "Sans chapitre",
    "btn.edit_db": "Modifier BD", "btn.close_edit": "✕ Fermer", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Créer PR", "btn.add": "Ajouter", "btn.add_chapter": "Ajouter Chapitre",
    "input.title": "Titel", "input.url": "https://...", "input.new_chapter": "Nouveau nom de chapitre...",
    "sec.shortcuts": "Mes Raccourcis", "sec.chapters": "📑 Gestionnaire de chapitres", "sec.no_chapters": "Aucun chapitre défini.", "sec.session": "⏱ Succès de session", "sec.guides": "📚 Guides communautaires",
    "db.available": "✓ BD communautaire disponible", "db.missing": "⚠ Pas de BD communautaire"
  },
  "es": {
    "menu.view": "Ver", "menu.themes": "Temas", "menu.accounts": "Cuentas", "menu.alwaysOnTop": "Siempre visible", "menu.overlayWarning": "⚠️ Configura tu juego en Modo Ventana sin Bordes para overlay", "menu.miniMode": "Modo Mini", "menu.windowMode": "Modo Ventana", "menu.opacity": "Opacidad", "menu.uiScale": "Escala UI", "menu.language": "Idioma", "menu.sound": "Sonido de logro", "menu.keys": "🔑 Gestionar claves API", "menu.startup": "Ejecutar al inicio del sistema", "menu.screenshots": "Carpeta de Capturas",
    "filter.all": "Todos", "filter.locked": "Bloqueado", "filter.unlocked": "Desbloqueado", "filter.tracked": "Rastreado", "filter.missable": "⚠️ Perdible", "filter.spoilers": "👁 Spoilers", "filter.guided": "🛡 Modo Guiado", "filter.guidedOn": "🛡 Modo Guiado (ON)", "menu.links": "Enlaces",
    "search.achievements": "Buscar logros...", "search.library": "🔍 Buscar juegos...",
    "lib.title": "Biblioteca", "lib.empty": "No hay juegos.", "lib.all": "Todos", "lib.in_progress": "En progreso", "lib.complete": "Completo", "lib.not_started": "Sin empezar", "lib.abandoned": "Abandonado", "lib.last_played": "Recientes", "lib.name_az": "Nombre A–Z", "lib.most_complete": "Más completados", "lib.least_complete": "Menos completados",
    "status.live": "Jugando", "status.offline": "Desconectado", "status.unlocked": "Desbloqueados",
    "stat.avgCompletion": "Completado promedio", "stat.rarityDist": "Distribución de Rareza",
    "accordion.stats": "Estadísticas y Rareza", "accordion.shortcuts": "Mis Atajos",
    "sort.api": "Orden API", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Más raros primero", "sort.common": "Más comunes primero", "sort.chapter": "Capítulos",
    "card.achievements": "logros", "card.play": "▶ Jugar", "card.rarest": "⭐ Más raro:", "card.running": "Ejecutándose",
    "chap.all": "Todos los capítulos", "chap.none": "-- Sin capítulo --", "chap.fallback": "Sin capítulo",
    "btn.edit_db": "Editar BD", "btn.close_edit": "✕ Cerrar", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Crear PR", "btn.add": "Añadir", "btn.add_chapter": "Añadir capítulo",
    "input.title": "Título", "input.url": "https://...", "input.new_chapter": "Nombre de capítulo...",
    "sec.shortcuts": "Mis Atajos", "sec.chapters": "📑 Gestor de capítulos", "sec.no_chapters": "Sin capítulos.", "sec.session": "⏱ Logros de sesión", "sec.guides": "📚 Guías de comunidad",
    "db.available": "✓ BD comunitaria disponible", "db.missing": "⚠ Sin BD comunitaria"
  },
  "es-419": {
    "menu.view": "Ver", "menu.themes": "Temas", "menu.accounts": "Cuentas", "menu.alwaysOnTop": "Siempre visible", "menu.overlayWarning": "⚠️ Configura el juego en Ventana sin Bordes para overlay", "menu.miniMode": "Modo Mini", "menu.windowMode": "Modo Ventana", "menu.opacity": "Opacidad", "menu.uiScale": "Escala UI", "menu.language": "Idioma", "menu.sound": "Sonido de logro", "menu.keys": "🔑 Administrar API", "menu.startup": "Ejecutar al iniciar el sistema", "menu.screenshots": "Carpeta de Capturas",
    "filter.all": "Todos", "filter.locked": "Bloqueado", "filter.unlocked": "Desbloqueado", "filter.tracked": "Rastreado", "filter.missable": "⚠️ Perdible", "filter.spoilers": "👁 Spoilers", "filter.guided": "🛡 Modo Guiado", "filter.guidedOn": "🛡 Modo Guiado (ON)", "menu.links": "Enlaces",
    "search.achievements": "Buscar logros...", "search.library": "🔍 Buscar juegos...",
    "lib.title": "Biblioteca", "lib.empty": "No hay juegos.", "lib.all": "Todos", "lib.in_progress": "En progreso", "lib.complete": "Completo", "lib.not_started": "Sin empezar", "lib.abandoned": "Abandonado", "lib.last_played": "Recientes", "lib.name_az": "Nombre A–Z", "lib.most_complete": "Más completados", "lib.least_complete": "Menos completados",
    "status.live": "Jugando", "status.offline": "Desconectado", "status.unlocked": "Desbloqueados",
    "stat.avgCompletion": "Completado global", "stat.rarityDist": "Distribución de Rareza",
    "accordion.stats": "Estadísticas y Rareza", "accordion.shortcuts": "Mis Atajos",
    "sort.api": "Orden API", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Más raros primero", "sort.common": "Más comunes primero", "sort.chapter": "Capítulos",
    "card.achievements": "logros", "card.play": "▶ Jugar", "card.rarest": "⭐ Más raro:", "card.running": "Ejecutándose",
    "chap.all": "Todos los capítulos", "chap.none": "-- Sin capítulo --", "chap.fallback": "Sin capítulo",
    "btn.edit_db": "Editar BD", "btn.close_edit": "✕ Cerrar", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Crear PR", "btn.add": "Agregar", "btn.add_chapter": "Agregar capítulo",
    "input.title": "Título", "input.url": "https://...", "input.new_chapter": "Nombre de capítulo...",
    "sec.shortcuts": "Mis Atajos", "sec.chapters": "📑 Gestor de capítulos", "sec.no_chapters": "Sin capítulos.", "sec.session": "⏱ Logros de sesión", "sec.guides": "📚 Guías de la comunidad",
    "db.available": "✓ BD disponible", "db.missing": "⚠ Sin BD de la comunidad"
  },
  "pt-BR": {
    "menu.view": "Exibir", "menu.themes": "Temas", "menu.accounts": "Contas", "menu.alwaysOnTop": "Sempre no topo", "menu.overlayWarning": "⚠️ Use o modo Janela sem Bordas para usar o overlay", "menu.miniMode": "Modo Mini", "menu.windowMode": "Modo Janela", "menu.opacity": "Opacidade", "menu.uiScale": "Escala UI", "menu.language": "Idioma", "menu.sound": "Som de Conquista", "menu.keys": "🔑 Gerenciar Chaves API", "menu.startup": "Iniciar com o sistema", "menu.screenshots": "Pasta de Capturas",
    "filter.all": "Todos", "filter.locked": "Bloqueado", "filter.unlocked": "Desbloqueado", "filter.tracked": "Marcado", "filter.missable": "⚠️ Perdível", "filter.spoilers": "👁 Spoilers", "filter.guided": "🛡 Modo Guiado", "filter.guidedOn": "🛡 Modo Guiado (ON)", "menu.links": "Links",
    "search.achievements": "Buscar conquistas...", "search.library": "🔍 Buscar jogos...",
    "lib.title": "Biblioteca", "lib.empty": "Nenhum jogo encontrado.", "lib.all": "Todos", "lib.in_progress": "Em progresso", "lib.complete": "Completo", "lib.not_started": "Não iniciado", "lib.abandoned": "Abandonado", "lib.last_played": "Recentes", "lib.name_az": "Nome A–Z", "lib.most_complete": "Mais completos", "lib.least_complete": "Menos completos",
    "status.live": "Jogando", "status.offline": "Offline", "status.unlocked": "Desbloqueadas",
    "stat.avgCompletion": "Conclusão Média", "stat.rarityDist": "Distribuição de Raridade",
    "accordion.stats": "Estatísticas e Raridade", "accordion.shortcuts": "Meus Atalhos",
    "sort.api": "Ordem da API", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Mais raras primeiro", "sort.common": "Mais comuns primeiro", "sort.chapter": "Capítulos",
    "card.achievements": "conquistas", "card.play": "▶ Jogar", "card.rarest": "⭐ Mais rara:", "card.running": "Executando",
    "chap.all": "Todos os capítulos", "chap.none": "-- Sem capítulo --", "chap.fallback": "Sem capítulo",
    "btn.edit_db": "Editar BD", "btn.close_edit": "✕ Fechar", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Criar PR", "btn.add": "Adicionar", "btn.add_chapter": "Adicionar capítulo",
    "input.title": "Título", "input.url": "https://...", "input.new_chapter": "Nome do capítulo...",
    "sec.shortcuts": "Meus Atalhos", "sec.chapters": "📑 Gerenciador de capítulos", "sec.no_chapters": "Sem capítulos.", "sec.session": "⏱ Conquistas da sessão", "sec.guides": "📚 Guias da comunidade",
    "db.available": "✓ BD da comunidade disponível", "db.missing": "⚠ Sem BD da comunidade"
  },
  "pt-PT": {
    "menu.view": "Ver", "menu.themes": "Temas", "menu.accounts": "Contas", "menu.alwaysOnTop": "Sempre visível", "menu.overlayWarning": "⚠️ Usa o modo Janela sem Bordas para usar a sobreposição", "menu.miniMode": "Modo Mini", "menu.windowMode": "Modo de Janela", "menu.opacity": "Opacidade", "menu.uiScale": "Escala UI", "menu.language": "Idioma", "menu.sound": "Som de Conquista", "menu.keys": "🔑 Gerir Chaves API", "menu.startup": "Iniciar com o sistema", "menu.screenshots": "Pasta de Capturas",
    "filter.all": "Todos", "filter.locked": "Bloqueado", "filter.unlocked": "Desbloqueado", "filter.tracked": "Seguido", "filter.missable": "⚠️ Perdível", "filter.spoilers": "👁 Spoilers", "filter.guided": "🛡 Modo Guiado", "filter.guidedOn": "🛡 Modo Guiado (ON)", "menu.links": "Links",
    "search.achievements": "Procurar conquistas...", "search.library": "🔍 Procurar jogos...",
    "lib.title": "Biblioteca", "lib.empty": "Nenhum jogo encontrado.", "lib.all": "Todos", "lib.in_progress": "Em curso", "lib.complete": "Completo", "lib.not_started": "Não iniciado", "lib.abandoned": "Abandonado", "lib.last_played": "Jogados recentemente", "lib.name_az": "Nome A–Z", "lib.most_complete": "Mais completos", "lib.least_complete": "Menos completos",
    "status.live": "A Jogar", "status.offline": "Offline", "status.unlocked": "Desbloqueadas",
    "stat.avgCompletion": "Conclusão Média Global", "stat.rarityDist": "Distribuição de Raridade",
    "accordion.stats": "Estatísticas e Raridade", "accordion.shortcuts": "Os Meus Atalhos",
    "sort.api": "Ordem da API", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Mais raras primeiro", "sort.common": "Mais comuns primeiro", "sort.chapter": "Ordem de Capítulos",
    "card.achievements": "conquistas", "card.play": "▶ Jogar", "card.rarest": "⭐ Mais rara:", "card.running": "A Executar",
    "chap.all": "Todos os capítulos", "chap.none": "-- Sem capítulo --", "chap.fallback": "Sem capítulo",
    "btn.edit_db": "Editar BD", "btn.close_edit": "✕ Fechar", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Criar PR", "btn.add": "Adicionar", "btn.add_chapter": "Adicionar capítulo",
    "input.title": "Título", "input.url": "https://...", "input.new_chapter": "Nome do capítulo...",
    "sec.shortcuts": "Os Meus Atalhos", "sec.chapters": "📑 Gestor de capítulos", "sec.no_chapters": "Sem capítulos definidos.", "sec.session": "⏱ Conquistas da sessão", "sec.guides": "📚 Guias da comunidade",
    "db.available": "✓ BD da comunidade disponível", "db.missing": "⚠ Sem BD da comunidade"
  },
  "it": {
    "menu.view": "Visualizza", "menu.themes": "Temi", "menu.accounts": "Account", "menu.alwaysOnTop": "Sempre in primo piano", "menu.overlayWarning": "⚠️ Imposta il gioco su Finestra senza bordi per l'overlay", "menu.miniMode": "Modalità Mini", "menu.windowMode": "Modalità Finestra", "menu.opacity": "Opacità", "menu.uiScale": "Scala UI", "menu.language": "Lingua", "menu.sound": "Suono di sblocco", "menu.keys": "🔑 Gestisci chiavi API", "menu.startup": "Esegui all'avvio del sistema", "menu.screenshots": "Cartella Screenshot",
    "filter.all": "Tutti", "filter.locked": "Bloccati", "filter.unlocked": "Sbloccati", "filter.tracked": "Seguiti", "filter.missable": "⚠️ Mancabili", "filter.spoilers": "👁 Spoiler", "filter.guided": "🛡 Modalità Guidata", "filter.guidedOn": "🛡 Modalità Guidata (ON)", "menu.links": "Link",
    "search.achievements": "Cerca obiettivi...", "search.library": "🔍 Cerca giochi...",
    "lib.title": "Libreria", "lib.empty": "Nessun gioco trovato.", "lib.all": "Tutti", "lib.in_progress": "In corso", "lib.complete": "Completato", "lib.not_started": "Non iniziato", "lib.abandoned": "Abbandonato", "lib.last_played": "Giocati di recente", "lib.name_az": "Nome A–Z", "lib.most_complete": "Più completati", "lib.least_complete": "Meno completati",
    "status.live": "In gioco", "status.offline": "Offline", "status.unlocked": "Sbloccati",
    "stat.avgCompletion": "Completamento medio", "stat.rarityDist": "Distribuzione rarità",
    "accordion.stats": "Statistiche e Rarità", "accordion.shortcuts": "Le mie Scorciatoie",
    "sort.api": "Ordine API", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Più rari prima", "sort.common": "Più comuni prima", "sort.chapter": "Capitoli",
    "card.achievements": "obiettivi", "card.play": "▶ Gioca", "card.rarest": "⭐ Più raro:", "card.running": "In esecuzione",
    "chap.all": "Tutti i capitoli", "chap.none": "-- Nessun capitolo --", "chap.fallback": "Nessun capitolo",
    "btn.edit_db": "Modifica DB", "btn.close_edit": "✕ Chiudi", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Crea PR", "btn.add": "Aggiungi", "btn.add_chapter": "Aggiungi Capitolo",
    "input.title": "Titolo", "input.url": "https://...", "input.new_chapter": "Nome capitolo...",
    "sec.shortcuts": "Le mie Scorciatoie", "sec.chapters": "📑 Gestore Capitoli", "sec.no_chapters": "Nessun capitolo.", "sec.session": "⏱ Obiettivi della sessione", "sec.guides": "📚 Guide della community",
    "db.available": "✓ DB community disponibile", "db.missing": "⚠ Nessun DB community"
  },
  "pl": {
    "menu.view": "Widok", "menu.themes": "Motywy", "menu.accounts": "Konta", "menu.alwaysOnTop": "Zawsze na wierzchu", "menu.overlayWarning": "⚠️ Aby użyć nakładki, ustaw grę w trybie okna bez ramek", "menu.miniMode": "Tryb Mini", "menu.windowMode": "Tryb okna", "menu.opacity": "Krycie", "menu.uiScale": "Skala interfejsu", "menu.language": "Język", "menu.sound": "Dźwięk odblokowania", "menu.keys": "🔑 Zarządzaj kluczami API", "menu.startup": "Uruchamiaj przy starcie systemu", "menu.screenshots": "Folder Zrzutów Ekranu",
    "filter.all": "Wszystkie", "filter.locked": "Zablokowane", "filter.unlocked": "Odblokowane", "filter.tracked": "Śledzone", "filter.missable": "⚠️ Pomijalne", "filter.spoilers": "👁 Spoilery", "filter.guided": "🛡 Tryb Z Przewodnikiem", "filter.guidedOn": "🛡 Tryb Z Przewodnikiem (WŁ)", "menu.links": "Linki",
    "search.achievements": "Szukaj osiągnięć...", "search.library": "🔍 Szukaj gier...",
    "lib.title": "Biblioteka", "lib.empty": "Brak gier.", "lib.all": "Wszystkie", "lib.in_progress": "W trakcie", "lib.complete": "Ukończone", "lib.not_started": "Nierozpoczęte", "lib.abandoned": "Porzucone", "lib.last_played": "Ostatnio grane", "lib.name_az": "Nazwa A–Z", "lib.most_complete": "Najwięcej ukończonych", "lib.least_complete": "Najmniej ukończonych",
    "status.live": "W grze", "status.offline": "Offline", "status.unlocked": "Odblokowano",
    "stat.avgCompletion": "Średnie ukończenie", "stat.rarityDist": "Rozkład Rzadkości",
    "accordion.stats": "Statystyki i Rzadkość", "accordion.shortcuts": "Moje Skróty",
    "sort.api": "Kolejność API", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Najrzadsze najpierw", "sort.common": "Najczęstsze najpierw", "sort.chapter": "Rozdziały",
    "card.achievements": "osiągnięć", "card.play": "▶ Graj", "card.rarest": "⭐ Najrzadsze:", "card.running": "Uruchomiona",
    "chap.all": "Wszystkie rozdziały", "chap.none": "-- Brak rozdziału --", "chap.fallback": "Brak rozdziału",
    "btn.edit_db": "Edytuj DB", "btn.close_edit": "✕ Zamknij", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Utwórz PR", "btn.add": "Dodaj", "btn.add_chapter": "Dodaj rozdział",
    "input.title": "Tytuł", "input.url": "https://...", "input.new_chapter": "Nazwa rozdziału...",
    "sec.shortcuts": "Moje Skróty", "sec.chapters": "📑 Menedżer Rozdziałów", "sec.no_chapters": "Brak rozdziałów.", "sec.session": "⏱ Osiągnięcia sesji", "sec.guides": "📚 Poradniki społeczności",
    "db.available": "✓ Baza społeczności dostępna", "db.missing": "⚠ Brak bazy społeczności"
  },
  "ru": {
    "menu.view": "Вид", "menu.themes": "Темы", "menu.accounts": "Аккаунты", "menu.alwaysOnTop": "Поверх всех окон", "menu.overlayWarning": "⚠️ Для работы оверлея включите Оконный режим без рамок в игре", "menu.miniMode": "Компактный режим", "menu.windowMode": "Режим окна", "menu.opacity": "Прозрачность", "menu.uiScale": "Масштаб интерфейса", "menu.language": "Язык", "menu.sound": "Звук разблокировки", "menu.keys": "🔑 Управление API-ключами", "menu.startup": "Запускать при старте системы", "menu.screenshots": "Папка со скриншотами",
    "filter.all": "Все", "filter.locked": "Заблокированы", "filter.unlocked": "Открыты", "filter.tracked": "Отслеживаемые", "filter.missable": "⚠️ Пропускаемые", "filter.spoilers": "👁 Спойлеры", "filter.guided": "🛡 Режим гида", "filter.guidedOn": "🛡 Режим гида (ВКЛ)", "menu.links": "Ссылки",
    "search.achievements": "Поиск достижений...", "search.library": "🔍 Поиск игр...",
    "lib.title": "Библиотека", "lib.empty": "Игры не найдены.", "lib.all": "Все", "lib.in_progress": "В процессе", "lib.complete": "Пройдено", "lib.not_started": "Не начато", "lib.abandoned": "Заброшено", "lib.last_played": "Недавние", "lib.name_az": "Имя А–Я", "lib.most_complete": "Больше достижений", "lib.least_complete": "Меньше достижений",
    "status.live": "В игре", "status.offline": "Не в сети", "status.unlocked": "Открыто",
    "stat.avgCompletion": "Средний % открытия", "stat.rarityDist": "Распределение редкости",
    "accordion.stats": "Статистика и редкость", "accordion.shortcuts": "Мои ярлыки",
    "sort.api": "Порядок API", "sort.az": "А - Я", "sort.za": "Я - А", "sort.rarest": "Сначала редкие", "sort.common": "Сначала частые", "sort.chapter": "По главам",
    "card.achievements": "достиж.", "card.play": "▶ Играть", "card.rarest": "⭐ Редчайшее:", "card.running": "Запущена",
    "chap.all": "Все главы", "chap.none": "-- Без главы --", "chap.fallback": "Без главы",
    "btn.edit_db": "Ред. БД", "btn.close_edit": "✕ Закрыть", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Создать PR", "btn.add": "Добавить", "btn.add_chapter": "Добавить главу",
    "input.title": "Название", "input.url": "https://...", "input.new_chapter": "Название главы...",
    "sec.shortcuts": "Мои ярлыки", "sec.chapters": "📑 Менеджер глав", "sec.no_chapters": "Главы не заданы.", "sec.session": "⏱ Достижения за сеанс", "sec.guides": "📚 Руководства",
    "db.available": "✓ База сообщества доступна", "db.missing": "⚠ Нет базы сообщества"
  },
  "uk": {
    "menu.view": "Вигляд", "menu.themes": "Теми", "menu.accounts": "Акаунти", "menu.alwaysOnTop": "Поверх усіх вікон", "menu.overlayWarning": "⚠️ Для використання оверлею увімкніть Віконний режим без рамок у грі", "menu.miniMode": "Компактний режим", "menu.windowMode": "Режим вікна", "menu.opacity": "Прозорість", "menu.uiScale": "Масштаб інтерфейсу", "menu.language": "Мова", "menu.sound": "Звук розблокування", "menu.keys": "🔑 Керування ключами API", "menu.startup": "Запускати під час старту системи", "menu.screenshots": "Папка зі скріншотами",
    "filter.all": "Всі", "filter.locked": "Заблоковані", "filter.unlocked": "Відкриті", "filter.tracked": "Відстежувані", "filter.missable": "⚠️ Ті, що пропускаються", "filter.spoilers": "👁 Спойлери", "filter.guided": "🛡 Режим гіда", "filter.guidedOn": "🛡 Режим гіда (УВІМК)", "menu.links": "Посилання",
    "search.achievements": "Пошук досягнень...", "search.library": "🔍 Пошук ігор...",
    "lib.title": "Бібліотека", "lib.empty": "Ігри не знайдено.", "lib.all": "Всі", "lib.in_progress": "В процесі", "lib.complete": "Пройдено", "lib.not_started": "Не розпочато", "lib.abandoned": "Покинуто", "lib.last_played": "Недавні", "lib.name_az": "Ім'я А–Я", "lib.most_complete": "Більше досягнень", "lib.least_complete": "Менше досягнень",
    "status.live": "У грі", "status.offline": "Не в мережі", "status.unlocked": "Відкрито",
    "stat.avgCompletion": "Середній % відкриття", "stat.rarityDist": "Розподіл рідкості",
    "accordion.stats": "Статистика та рідкість", "accordion.shortcuts": "Мої ярлики",
    "sort.api": "Порядок API", "sort.az": "А - Я", "sort.za": "Я - А", "sort.rarest": "Спочатку рідкісні", "sort.common": "Спочатку часті", "sort.chapter": "За главами",
    "card.achievements": "досягн.", "card.play": "▶ Грати", "card.rarest": "⭐ Найрідкісніше:", "card.running": "Запущена",
    "chap.all": "Всі глави", "chap.none": "-- Без глави --", "chap.fallback": "Без глави",
    "btn.edit_db": "Ред. БД", "btn.close_edit": "✕ Закрити", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Створити PR", "btn.add": "Додати", "btn.add_chapter": "Додати главу",
    "input.title": "Назва", "input.url": "https://...", "input.new_chapter": "Назва глави...",
    "sec.shortcuts": "Мої ярлики", "sec.chapters": "📑 Менеджер глав", "sec.no_chapters": "Глави не задані.", "sec.session": "⏱ Досягнення за сеанс", "sec.guides": "📚 Посібники",
    "db.available": "✓ База спільноти доступна", "db.missing": "⚠ Немає бази спільноти"
  },
  "zh-CN": {
    "menu.view": "视图", "menu.themes": "主题", "menu.accounts": "账户", "menu.alwaysOnTop": "总在最前", "menu.overlayWarning": "⚠️ 若要使用覆盖，请将游戏设为无边框窗口模式", "menu.miniMode": "迷你模式", "menu.windowMode": "窗口模式", "menu.opacity": "窗口透明度", "menu.uiScale": "界面缩放", "menu.language": "语言", "menu.sound": "解锁音效", "menu.keys": "🔑 管理 API 密钥",
    "filter.all": "全部", "filter.locked": "未解锁", "filter.unlocked": "已解锁", "filter.tracked": "正在追踪", "filter.missable": "⚠️ 易错过", "filter.spoilers": "👁 剧透", "filter.guided": "🛡 指导模式", "filter.guidedOn": "🛡 指导模式 (开)", "menu.startup": "开机自动运行", "menu.screenshots": "截图文件夹",
    "search.achievements": "搜索成就...", "search.library": "🔍 搜索游戏...", "menu.links": "链接",
    "lib.title": "库", "lib.empty": "没有找到游戏。", "lib.all": "全部", "lib.in_progress": "进行中", "lib.complete": "已完成", "lib.not_started": "未开始", "lib.abandoned": "已放弃", "lib.last_played": "最近游玩", "lib.name_az": "名称 A-Z", "lib.most_complete": "完成度最高", "lib.least_complete": "完成度最低",
    "status.live": "游戏中", "status.offline": "离线", "status.unlocked": "已解锁",
    "stat.avgCompletion": "全球平均完成率", "stat.rarityDist": "稀有度分布",
    "accordion.stats": "统计与稀有度", "accordion.shortcuts": "我的快捷方式",
    "sort.api": "默认排序", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "最稀有优先", "sort.common": "最常见优先", "sort.chapter": "章节顺序",
    "card.achievements": "项成就", "card.play": "▶ 游玩", "card.rarest": "⭐ 最稀有:", "card.running": "运行中",
    "chap.all": "所有章节", "chap.none": "-- 无章节 --", "chap.fallback": "无章节",
    "btn.edit_db": "编辑数据库", "btn.close_edit": "✕ 关闭", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "创建 PR", "btn.add": "添加", "btn.add_chapter": "添加章节",
    "input.title": "标题", "input.url": "https://...", "input.new_chapter": "新章节名称...",
    "sec.shortcuts": "我的快捷方式", "sec.chapters": "📑 章节管理器", "sec.no_chapters": "未定义章节。", "sec.session": "⏱ 本次游玩解锁", "sec.guides": "📚 社区指南",
    "db.available": "✓ 社区数据库可用", "db.missing": "⚠ 暂无社区数据库"
  },
  "zh-TW": {
    "menu.view": "檢視", "menu.themes": "主題", "menu.accounts": "帳戶", "menu.alwaysOnTop": "總在最前", "menu.overlayWarning": "⚠️ 若要使用覆疊，請將遊戲設為無邊框視窗模式", "menu.miniMode": "迷你模式", "menu.windowMode": "視窗模式", "menu.opacity": "視窗透明度", "menu.uiScale": "介面縮放", "menu.language": "語言", "menu.sound": "解鎖音效", "menu.keys": "🔑 管理 API 金鑰",
    "filter.all": "全部", "filter.locked": "未解鎖", "filter.unlocked": "已解鎖", "filter.tracked": "正在追蹤", "filter.missable": "⚠️ 易錯過", "filter.spoilers": "👁 劇透", "filter.guided": "🛡 指導模式", "filter.guidedOn": "🛡 指導模式 (開)", "menu.startup": "開機自動執行", "menu.screenshots": "截圖資料夾",
    "search.achievements": "搜尋成就...", "search.library": "🔍 搜尋遊戲...", "menu.links": "連結",
    "lib.title": "庫", "lib.empty": "沒有找到遊戲。", "lib.all": "全部", "lib.in_progress": "進行中", "lib.complete": "已完成", "lib.not_started": "未開始", "lib.abandoned": "已放棄", "lib.last_played": "最近遊玩", "lib.name_az": "名稱 A-Z", "lib.most_complete": "完成度最高", "lib.least_complete": "完成度最低",
    "status.live": "遊戲中", "status.offline": "離線", "status.unlocked": "已解鎖",
    "stat.avgCompletion": "全球平均完成率", "stat.rarityDist": "稀有度分佈",
    "accordion.stats": "統計與稀有度", "accordion.shortcuts": "我的捷徑",
    "sort.api": "預設排序", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "最稀有優先", "sort.common": "最常見優先", "sort.chapter": "章節順序",
    "card.achievements": "項成就", "card.play": "▶ 遊玩", "card.rarest": "⭐ 最稀有:", "card.running": "執行中",
    "chap.all": "所有章節", "chap.none": "-- 無章節 --", "chap.fallback": "無章節",
    "btn.edit_db": "編輯資料庫", "btn.close_edit": "✕ 關閉", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "建立 PR", "btn.add": "新增", "btn.add_chapter": "新增章節",
    "input.title": "標題", "input.url": "https://...", "input.new_chapter": "新章節名稱...",
    "sec.shortcuts": "我的捷徑", "sec.chapters": "📑 章節管理員", "sec.no_chapters": "未定義章節。", "sec.session": "⏱ 本次遊玩解鎖", "sec.guides": "📚 社群指南",
    "db.available": "✓ 社群資料庫可用", "db.missing": "⚠ 暫無社群資料庫"
  },
  "ja": {
    "menu.view": "表示", "menu.themes": "テーマ", "menu.accounts": "アカウント", "menu.alwaysOnTop": "常に手前に表示", "menu.overlayWarning": "⚠️ オーバーレイを使用するにはゲームをボーダーレスウィンドウに設定してください", "menu.miniMode": "ミニモード", "menu.windowMode": "ウィンドウモード", "menu.opacity": "透明度", "menu.uiScale": "UIスケール", "menu.language": "言語", "menu.sound": "解除サウンド", "menu.keys": "🔑 APIキー管理", "menu.startup": "システム起動時に実行", "menu.screenshots": "スクリーンショット フォルダ",
    "filter.all": "すべて", "filter.locked": "未解除", "filter.unlocked": "解除済み", "filter.tracked": "追跡中", "filter.missable": "⚠️ 取り逃し注意", "filter.spoilers": "👁 ネタバレ", "filter.guided": "🛡 ガイドモード", "filter.guidedOn": "🛡 ガイドモード (オン)", "menu.links": "リンク",
    "search.achievements": "実績を検索...", "search.library": "🔍 ゲームを検索...",
    "lib.title": "ライブラリ", "lib.empty": "ゲームが見つかりません。", "lib.all": "すべて", "lib.in_progress": "プレイ中", "lib.complete": "コンプリート", "lib.not_started": "未プレイ", "lib.abandoned": "リタイア", "lib.last_played": "最近プレイ", "lib.name_az": "名前 A–Z", "lib.most_complete": "達成率が高い順", "lib.least_complete": "達成率が低い順",
    "status.live": "プレイ中", "status.offline": "オフライン", "status.unlocked": "解除済み",
    "stat.avgCompletion": "平均クリア率", "stat.rarityDist": "レアリティ分布",
    "accordion.stats": "統計とレアリティ", "accordion.shortcuts": "ショートカット",
    "sort.api": "デフォルト", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "レアな順", "sort.common": "一般的な順", "sort.chapter": "チャプター順",
    "card.achievements": "実績", "card.play": "▶ プレイ", "card.rarest": "⭐ 最もレア:", "card.running": "起動中",
    "chap.all": "すべてのチャプター", "chap.none": "-- チャプターなし --", "chap.fallback": "チャプターなし",
    "btn.edit_db": "DB編集", "btn.close_edit": "✕ 閉じる", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "PR作成", "btn.add": "追加", "btn.add_chapter": "チャプター追加",
    "input.title": "タイトル", "input.url": "https://...", "input.new_chapter": "新しいチャプター名...",
    "sec.shortcuts": "ショートカット", "sec.chapters": "📑 チャプター管理", "sec.no_chapters": "チャプターがありません", "sec.session": "⏱ 今回の解除実績", "sec.guides": "📚 コミュニティガイド",
    "db.available": "✓ コミュニティDB利用可能", "db.missing": "⚠ コミュニティDBなし"
  },
  "ko": {
    "menu.view": "보기", "menu.themes": "테마", "menu.accounts": "계정", "menu.alwaysOnTop": "항상 위", "menu.overlayWarning": "⚠️ 오버레이를 사용하려면 게임을 테두리 없는 창 모드로 설정하세요", "menu.miniMode": "미니 모드", "menu.windowMode": "창 모드", "menu.opacity": "투명도", "menu.uiScale": "UI 크기", "menu.language": "언어", "menu.sound": "잠금 해제 사운드", "menu.keys": "🔑 API 키 관리", "menu.screenshots": "스크린샷 폴더", "menu.links": "링크",
    "filter.all": "모두", "filter.locked": "잠김", "filter.unlocked": "잠금 해제됨", "filter.tracked": "추적 중", "filter.missable": "⚠️ 놓칠 수 있음", "filter.spoilers": "👁 스포일러", "filter.guided": "🛡 가이드 모드", "filter.guidedOn": "🛡 가이드 모드 (켜짐)", "menu.startup": "시스템 시작 시 자동 실행",
    "search.achievements": "도전 과제 검색...", "search.library": "🔍 게임 검색...",
    "lib.title": "라이브러리", "lib.empty": "게임을 찾을 수 없습니다.", "lib.all": "모두", "lib.in_progress": "진행 중", "lib.complete": "완료", "lib.not_started": "시작 안 함", "lib.abandoned": "포기함", "lib.last_played": "최근 플레이", "lib.name_az": "이름 A–Z", "lib.most_complete": "달성률 높은 순", "lib.least_complete": "달성률 낮은 순",
    "status.live": "게임 중", "status.offline": "오프라인", "status.unlocked": "잠금 해제됨",
    "stat.avgCompletion": "평균 달성률", "stat.rarityDist": "희귀도 분포",
    "accordion.stats": "통계 및 희귀도", "accordion.shortcuts": "내 바로 가기",
    "sort.api": "기본 순서", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "가장 희귀한 순", "sort.common": "가장 흔한 순", "sort.chapter": "챕터 순",
    "card.achievements": "도전 과제", "card.play": "▶ 플레이", "card.rarest": "⭐ 가장 희귀함:", "card.running": "실행 중",
    "chap.all": "모든 챕터", "chap.none": "-- 챕터 없음 --", "chap.fallback": "챕터 없음",
    "btn.edit_db": "DB 편집", "btn.close_edit": "✕ 닫기", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "PR 생성", "btn.add": "추가", "btn.add_chapter": "챕터 추가",
    "input.title": "제목", "input.url": "https://...", "input.new_chapter": "새 챕터 이름...",
    "sec.shortcuts": "내 바로 가기", "sec.chapters": "📑 챕터 관리자", "sec.no_chapters": "챕터가 없습니다.", "sec.session": "⏱ 이번 세션 잠금 해제", "sec.guides": "📚 커뮤니티 가이드",
    "db.available": "✓ 커뮤니티 DB 있음", "db.missing": "⚠ 커뮤니티 DB 없음"
  },
  "cs": {
    "menu.view": "Zobrazit", "menu.themes": "Motivy", "menu.accounts": "Účty", "menu.alwaysOnTop": "Vždy navrchu", "menu.overlayWarning": "⚠️ Pro použití překrytí nastavte hru do okna bez okrajů", "menu.miniMode": "Mini režim", "menu.windowMode": "Režim okna", "menu.opacity": "Krytí", "menu.uiScale": "Měřítko UI", "menu.language": "Jazyk", "menu.sound": "Zvuk odemčení", "menu.keys": "🔑 Spravovat klíče API", "menu.startup": "Spustit při startu systému", "menu.screenshots": "Složka Snímků Obrazovky",
    "filter.all": "Vše", "filter.locked": "Uzamčeno", "filter.unlocked": "Odemčeno", "filter.tracked": "Sledováno", "filter.missable": "⚠️ Minutelné", "filter.spoilers": "👁 Spoilery", "filter.guided": "🛡 Režim průvodce", "filter.guidedOn": "🛡 Průvodce (ZAP)", "menu.links": "Odkazy",
    "search.achievements": "Hledat achievementy...", "search.library": "🔍 Hledat hry...",
    "lib.title": "Knihovna", "lib.empty": "Nenalezeny žádné hry.", "lib.all": "Vše", "lib.in_progress": "Probíhá", "lib.complete": "Dokončeno", "lib.not_started": "Nezačato", "lib.abandoned": "Opuštěno", "lib.last_played": "Naposledy hráno", "lib.name_az": "Název A–Z", "lib.most_complete": "Nejvíce dokončené", "lib.least_complete": "Nejméně dokončené",
    "status.live": "Ve hře", "status.offline": "Offline", "status.unlocked": "Odemčeno",
    "stat.avgCompletion": "Průměrné dokončení", "stat.rarityDist": "Rozdělení vzácnosti",
    "accordion.stats": "Statistiky a Vzácnost", "accordion.shortcuts": "Moje Zkratky",
    "sort.api": "Pořadí API", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Nejvzácnější první", "sort.common": "Nejběžnější první", "sort.chapter": "Kapitoly",
    "card.achievements": "achievementů", "card.play": "▶ Hrát", "card.rarest": "⭐ Nejvzácnější:", "card.running": "Spuštěno",
    "chap.all": "Všechny kapitoly", "chap.none": "-- Žádná kapitola --", "chap.fallback": "Bez kapitoly",
    "btn.edit_db": "Upravit DB", "btn.close_edit": "✕ Zavřít", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Vytvořit PR", "btn.add": "Přidat", "btn.add_chapter": "Přidat kapitolu",
    "input.title": "Název", "input.url": "https://...", "input.new_chapter": "Název nové kapitoly...",
    "sec.shortcuts": "Moje Zkratky", "sec.chapters": "📑 Správce kapitol", "sec.no_chapters": "Žádné kapitoly.", "sec.session": "⏱ Odemčeno v relaci", "sec.guides": "📚 Komunitní návody",
    "db.available": "✓ Komunitní DB k dispozici", "db.missing": "⚠ Chybí komunitní DB"
  },
  "nl": {
    "menu.view": "Weergave", "menu.themes": "Thema's", "menu.accounts": "Accounts", "menu.alwaysOnTop": "Altijd op de voorgrond", "menu.overlayWarning": "⚠️ Gebruik Randloos Venster voor overlay-ondersteuning", "menu.miniMode": "Minimodus", "menu.windowMode": "Venstermodus", "menu.opacity": "Transparantie", "menu.uiScale": "UI-schaal", "menu.language": "Taal", "menu.sound": "Ontgrendelgeluid", "menu.keys": "🔑 API-sleutels beheren", "menu.startup": "Starten bij opstarten van systeem", "menu.screenshots": "Screenshotsmap",
    "filter.all": "Alles", "filter.locked": "Vergrendeld", "filter.unlocked": "Ontgrendeld", "filter.tracked": "Gevolgd", "filter.missable": "⚠️ Te missen", "filter.spoilers": "👁 Spoilers", "filter.guided": "🛡 Begeleide Modus", "filter.guidedOn": "🛡 Begeleide Modus (AAN)", "menu.links": "Links",
    "search.achievements": "Prestaties zoeken...", "search.library": "🔍 Spellen zoeken...",
    "lib.title": "Bibliotheek", "lib.empty": "Geen spellen gevonden.", "lib.all": "Alles", "lib.in_progress": "Bezig", "lib.complete": "Voltooid", "lib.not_started": "Niet gestart", "lib.abandoned": "Opgegeven", "lib.last_played": "Laatst gespeeld", "lib.name_az": "Naam A–Z", "lib.most_complete": "Meest voltooid", "lib.least_complete": "Minst voltooid",
    "status.live": "In-game", "status.offline": "Offline", "status.unlocked": "Ontgrendeld",
    "stat.avgCompletion": "Gemiddelde voltooiing", "stat.rarityDist": "Zeldzaamheidsverdeling",
    "accordion.stats": "Statistieken & Zeldzaamheid", "accordion.shortcuts": "Mijn Snelkoppelingen",
    "sort.api": "API Volgorde", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Zeldzaamste eerst", "sort.common": "Meest voorkomend eerst", "sort.chapter": "Hoofdstukken",
    "card.achievements": "prestaties", "card.play": "▶ Spelen", "card.rarest": "⭐ Zeldzaamste:", "card.running": "Wordt uitgevoerd",
    "chap.all": "Alle hoofdstukken", "chap.none": "-- Geen hoofdstuk --", "chap.fallback": "Geen hoofdstuk",
    "btn.edit_db": "DB bewerken", "btn.close_edit": "✕ Sluiten", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "PR Aanmaken", "btn.add": "Toevoegen", "btn.add_chapter": "Hoofdstuk toevoegen",
    "input.title": "Titel", "input.url": "https://...", "input.new_chapter": "Nieuwe hoofdstuknaam...",
    "sec.shortcuts": "Mijn Snelkoppelingen", "sec.chapters": "📑 Hoofdstukbeheerder", "sec.no_chapters": "Geen hoofdstukken.", "sec.session": "⏱ Sessie-ontgrendelingen", "sec.guides": "📚 Communitygidsen",
    "db.available": "✓ Community-DB beschikbaar", "db.missing": "⚠ Geen community-DB"
  },
  "th": {
    "menu.view": "มุมมอง", "menu.themes": "ธีม", "menu.accounts": "บัญชี", "menu.alwaysOnTop": "แสดงบนสุดเสมอ", "menu.overlayWarning": "⚠️ เพื่อใช้งานโอเวอร์เลย์ โปรดตั้งค่าเกมเป็นโหมดหน้าต่างไร้ขอบ", "menu.miniMode": "โหมดมินิ", "menu.windowMode": "โหมดหน้าต่าง", "menu.opacity": "ความทึบ", "menu.uiScale": "ขนาด UI", "menu.language": "ภาษา", "menu.sound": "เสียงปลดล็อก", "menu.keys": "🔑 จัดการ API Keys", "menu.startup": "เรียกใช้เมื่อเริ่มระบบ", "menu.screenshots": "โฟลเดอร์ภาพหน้าจอ",
    "filter.all": "ทั้งหมด", "filter.locked": "ล็อก", "filter.unlocked": "ปลดล็อกแล้ว", "filter.tracked": "กำลังติดตาม", "filter.missable": "⚠️ พลาดได้", "filter.spoilers": "👁 สปอยเลอร์", "filter.guided": "🛡 โหมดนำทาง", "filter.guidedOn": "🛡 โหมดนำทาง (เปิด)", "menu.links": "ลิงก์",
    "search.achievements": "ค้นหาความสำเร็จ...", "search.library": "🔍 ค้นหาเกม...",
    "lib.title": "คลังเกม", "lib.empty": "ไม่พบเกม", "lib.all": "ทั้งหมด", "lib.in_progress": "กำลังเล่น", "lib.complete": "เสร็จสิ้น", "lib.not_started": "ยังไม่เริ่ม", "lib.abandoned": "ล้มเลิก", "lib.last_played": "เล่นล่าสุด", "lib.name_az": "ชื่อ A-Z", "lib.most_complete": "เสร็จสมบูรณ์มากสุด", "lib.least_complete": "เสร็จสมบูรณ์น้อยสุด",
    "status.live": "กำลังเล่น", "status.offline": "ออฟไลน์", "status.unlocked": "ปลดล็อกแล้ว",
    "stat.avgCompletion": "อัตราสำเร็จเฉลี่ย", "stat.rarityDist": "การกระจายความหายาก",
    "accordion.stats": "สถิติ & ความหายาก", "accordion.shortcuts": "ทางลัดของฉัน",
    "sort.api": "ตาม API", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "หายากสุดก่อน", "sort.common": "พบบ่อยสุดก่อน", "sort.chapter": "ตามบท",
    "card.achievements": "ความสำเร็จ", "card.play": "▶ เล่น", "card.rarest": "⭐ หายากสุด:", "card.running": "กำลังทำงาน",
    "chap.all": "ทุกบท", "chap.none": "-- ไม่มีบท --", "chap.fallback": "ไม่มีบท",
    "btn.edit_db": "แก้ไข DB", "btn.close_edit": "✕ ปิด", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "สร้าง PR", "btn.add": "เพิ่ม", "btn.add_chapter": "เพิ่มบท",
    "input.title": "ชื่อ", "input.url": "https://...", "input.new_chapter": "ชื่อบทใหม่...",
    "sec.shortcuts": "ทางลัดของฉัน", "sec.chapters": "📑 ตัวจัดการบท", "sec.no_chapters": "ไม่ได้กำหนดบท", "sec.session": "⏱ ปลดล็อกในเซสชันนี้", "sec.guides": "📚 คู่มือชุมชน",
    "db.available": "✓ มี DB ของชุมชน", "db.missing": "⚠ ไม่มี DB ของชุมชน"
  },
  "vi": {
    "menu.view": "Hiển thị", "menu.themes": "Giao diện", "menu.accounts": "Tài khoản", "menu.alwaysOnTop": "Luôn trên cùng", "menu.overlayWarning": "⚠️ Để dùng overlay, hãy đặt game ở chế độ Cửa sổ không viền", "menu.miniMode": "Chế độ Mini", "menu.windowMode": "Chế độ cửa sổ", "menu.opacity": "Độ mờ", "menu.uiScale": "Kích thước UI", "menu.language": "Ngôn ngữ", "menu.sound": "Âm thanh mở khóa", "menu.keys": "🔑 Quản lý API Key", "menu.startup": "Chạy khi khởi động hệ thống", "menu.screenshots": "Thư mục Ảnh chụp màn hình",
    "filter.all": "Tất cả", "filter.locked": "Đã khóa", "filter.unlocked": "Đã mở", "filter.tracked": "Đang theo dõi", "filter.missable": "⚠️ Dễ bỏ lỡ", "filter.spoilers": "👁 Tiết lộ nội dung", "filter.guided": "🛡 Chế độ hướng dẫn", "filter.guidedOn": "🛡 Hướng dẫn (BẬT)", "menu.links": "Liên kết",
    "search.achievements": "Tìm thành tựu...", "search.library": "🔍 Tìm game...",
    "lib.title": "Thư viện", "lib.empty": "Không tìm thấy game.", "lib.all": "Tất cả", "lib.in_progress": "Đang chơi", "lib.complete": "Hoàn thành", "lib.not_started": "Chưa bắt đầu", "lib.abandoned": "Bỏ dở", "lib.last_played": "Chơi gần đây", "lib.name_az": "Tên A-Z", "lib.most_complete": "Hoàn thành nhiều nhất", "lib.least_complete": "Hoàn thành ít nhất",
    "status.live": "Đang trong game", "status.offline": "Ngoại tuyến", "status.unlocked": "Đã mở khóa",
    "stat.avgCompletion": "Hoàn thành trung bình", "stat.rarityDist": "Phân bố độ hiếm",
    "accordion.stats": "Thống kê & Độ hiếm", "accordion.shortcuts": "Lối tắt của tôi",
    "sort.api": "Mặc định", "sort.az": "A - Z", "sort.za": "Z - A", "sort.rarest": "Hiếm nhất trước", "sort.common": "Phổ biến trước", "sort.chapter": "Chương",
    "card.achievements": "thành tựu", "card.play": "▶ Chơi", "card.rarest": "⭐ Hiếm nhất:", "card.running": "Đang chạy",
    "chap.all": "Tất cả các chương", "chap.none": "-- Không có chương --", "chap.fallback": "Không có chương",
    "btn.edit_db": "Sửa DB", "btn.close_edit": "✕ Đóng", "btn.json": "⬇ JSON", "btn.html": "⬇ HTML", "btn.pr": "Tạo PR", "btn.add": "Thêm", "btn.add_chapter": "Thêm chương",
    "input.title": "Tiêu đề", "input.url": "https://...", "input.new_chapter": "Tên chương mới...",
    "sec.shortcuts": "Lối tắt", "sec.chapters": "📑 Quản lý chương", "sec.no_chapters": "Chưa có chương nào.", "sec.session": "⏱ Đã mở khóa", "sec.guides": "📚 Hướng dẫn cộng đồng",
    "db.available": "✓ Có sẵn DB cộng đồng", "db.missing": "⚠ Không có DB cộng đồng"
  }
};